// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaNM1TZH2K2LSyanmzrTwTZKeJi8LlppU',
    appId: '1:41452835629:web:f83bb526355ff66cebb9a4',
    messagingSenderId: '41452835629',
    projectId: 'dioptest-bb9e1',
    authDomain: 'dioptest-bb9e1.firebaseapp.com',
    storageBucket: 'dioptest-bb9e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB86zTFkua7o34ctBcY9g_tLMxaiP2Q1JQ',
    appId: '1:41452835629:android:aecfdb095f5d965febb9a4',
    messagingSenderId: '41452835629',
    projectId: 'dioptest-bb9e1',
    storageBucket: 'dioptest-bb9e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5Iagd6mecZPIAQL3zWE5bJA_D09pINE',
    appId: '1:41452835629:ios:768ce5e8ed2110caebb9a4',
    messagingSenderId: '41452835629',
    projectId: 'dioptest-bb9e1',
    storageBucket: 'dioptest-bb9e1.appspot.com',
    iosClientId: '41452835629-1p7m6b1vdhsavv6g63lekgucui2le03v.apps.googleusercontent.com',
    iosBundleId: 'com.example.diopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5Iagd6mecZPIAQL3zWE5bJA_D09pINE',
    appId: '1:41452835629:ios:768ce5e8ed2110caebb9a4',
    messagingSenderId: '41452835629',
    projectId: 'dioptest-bb9e1',
    storageBucket: 'dioptest-bb9e1.appspot.com',
    iosClientId: '41452835629-1p7m6b1vdhsavv6g63lekgucui2le03v.apps.googleusercontent.com',
    iosBundleId: 'com.example.diopapp',
  );
}
